stages:
  augment:
    cmd: python -m pipelines.augment
    deps:
    - pipelines/augment.py
    - src/augmentation.py
    - data/raw/train.csv
    - data/raw/train_images
    outs:
    - data/augmented/train_augmented.csv
    - data/augmented/train

  train_original:
    cmd: python -m pipelines.train
    deps:
    - pipelines/train.py
    - src/
    - data/raw/train.csv
    - data/raw/train_images
    params:
    - data.use_augmented
    - models
    - training
    metrics:
    - metrics_original.json:
        cache: false

  train_augmented:
    cmd: python -m pipelines.train
    deps:
    - pipelines/train.py
    - src/
    - data/augmented/train_augmented.csv
    - data/augmented/train
    params:
    - data.use_augmented
    - models
    - training
    metrics:
    - metrics_augmented.json:
        cache: false
params:
- dvclive_original/params.yaml
metrics:
- dvclive_original/metrics.json
plots:
- dvclive_original/plots/metrics:
    x: step
