train:
  batch_size: 32
  epochs: 5
  lr: 0.001
  model_name: "resnet18"  # варианты: smallcnn, resnet18, efficientnet_b0

data:
  train_path: data/train/
  csv_path: data/train.csv
  test_path: data/test/
  augment: false