data:
  original_csv: data/raw/train.csv
  original_img_dir: data/raw/train_images
  augmented_csv: data/augmented/train_augmented.csv
  augmented_img_dir: data/augmented/train
  use_augmented: false

models:
- SmallCNNAdaptive
- ResNet18
- EfficientNet-B0
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 3
